# Generated by Django 3.0.7 on 2021-02-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Аня', max_length=20, verbose_name='Имя')),
                ('surname', models.CharField(default='Зверева', max_length=20, verbose_name='Фамилияя')),
                ('xp', models.IntegerField(default=1)),
                ('description', models.TextField(verbose_name='Описание')),
                ('type1', models.CharField(choices=[('Б', 'Босс'), ('СР', 'Спортивная рота'), ('МО', 'Медицинский отряд'), ('НГ', 'Наукоград'), ('КК', 'Кулинарный колледж')], default='СР', max_length=150, verbose_name='Тип')),
            ],
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='Style',
        ),
    ]
