# Generated by Django 3.0.7 on 2021-03-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_anna_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anna',
            name='type1',
            field=models.CharField(choices=[('Босс', 'Босс'), ('Спортивная рота', 'Спортивная рота'), ('Медицинский отряд', 'Медицинский отряд'), ('Наукоград', 'Наукоград'), ('Кулинарный колледж', 'Кулинарный колледж')], default='СР', max_length=150, verbose_name='Тип'),
        ),
    ]
